pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id 'fabric-loom' version '1.18.3'
        id 'net.fabricmc.fabric-loom' version '1.18.3'
    }
}

rootProject.name = 'nogamble'

include 'common'
include 'versions:1.21.11'
include 'versions:26.1.2'
