plugins {
    id 'net.fabricmc.fabric-loom' version "${rootProject.loom_version}"
    id 'maven-publish'
}

base {
    archivesName = "${rootProject.archives_base_name}"
}
version = "${rootProject.mod_version}+mc${project.minecraft_version}"

sourceSets {
    main {
        java {
            srcDirs += rootProject.file('common/src/main/java')
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${rootProject.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

processResources {
    inputs.property "version", rootProject.mod_version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", rootProject.loader_version

    filesMatching("fabric.mod.json") {
        expand "version": rootProject.mod_version,
               "minecraft_version": project.minecraft_version,
               "loader_version": rootProject.loader_version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
    it.options.encoding = "UTF-8"
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from(rootProject.file("LICENSE")) {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}
